### ISSUE TITLE
ENV[ ] registeration

### ISSUE THREAD

**Issue by lujiayou123** [katerakelly/oyster#1]
Thank you very much for releasing the code!
When I try to run experiment 'ant-dir' , problem occured as shown below:
It seems that 'ant-dir' is not registered in ENV[ ] list , only 'cheetah-vel' ,'sparse-point-robot' and 'point-robot'.
So , how should I register all of the envs in oyster/rlkit/envs into ENVS[ ] list?
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###   
python launch_experiment.py ./configs/ant-dir.json

print ENVS[ ]: {'cheetah-vel': <class 'rlkit.envs.half_cheetah_vel.HalfCheetahVelEnv'>, 'sparse-point-robot': <class 'rlkit.envs.point_robot.SparsePointEnv'>, 'point-robot': <class 'rlkit.envs.point_robot.PointEnv'>}

Traceback (most recent call last):
  File "launch_experiment.py", line 144, in <module>
    main()
  File "/home/ljy/anaconda3/envs/pearl/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ljy/anaconda3/envs/pearl/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ljy/anaconda3/envs/pearl/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ljy/anaconda3/envs/pearl/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "launch_experiment.py", line 141, in main
    experiment(variant)
  File "launch_experiment.py", line 29, in experiment
    env = NormalizedBoxEnv(ENVS[variant['env_name']]  (**variant['env_params']))
KeyError: 'ant-dir'

**Comment by katerakelly** [comment]
Thanks for pointing this out! I've registered the rest of the envs, see this [https://github.com/katerakelly/oyster/commit/cea88c05f2944b68a2d9c426ac0d186432e24cb6](commit)

**Comment by lujiayou123** [comment]
Thank you very much




| |
陆嘉猷
邮箱：15261868763@163.com
|

签名由 网易邮箱大师 定制

On 04/30/2019 13:55, Kate Rakelly wrote:

Closed #1.
